### ISSUE TITLE
h8mail unable to launch 

### ISSUE THREAD

**Issue by asciiterminal** [khast3x/h8mail#42]
when ever i manage to launch h8mail using the command `h8mail ` or even `h8mail -h`
i get this following error
`Traceback (most recent call last):
  File "/usr/local/bin/h8mail", line 11, in <module>
    load_entry_point('h8mail==2.3', 'console_scripts', 'h8mail')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/h8mail-2.3-py2.7.egg/h8mail/__main__.py", line 2, in <module>
    from .utils.run import main
  File "/usr/local/lib/python2.7/dist-packages/h8mail-2.3-py2.7.egg/h8mail/utils/run.py", line 10, in <module>
    from .breachcompilation import breachcomp_check
  File "/usr/local/lib/python2.7/dist-packages/h8mail-2.3-py2.7.egg/h8mail/utils/breachcompilation.py", line 18
    c.info_news(f"Looking up {t.target} in BreachCompilation")
                                                            ^
SyntaxError: invalid syntax
`

**Comment by khast3x** [comment]
Hello, what python version did you launch h8mail with?

**Comment by omer-tech** [comment]
@asciiterminal I had the same issue, it is from using the wrong version of pip/python.

Verify you have pip3 and python3 installed
$ pip --version
$ python --version

If you have both python 2.x and python 3.x installed, you'll need to specify using python3 for the install using pip3

$ sudo pip3 uninstall h8mail
$ sudo pip3 install h8mail
