### ISSUE TITLE
No output written to CSV output file

### ISSUE THREAD

**Issue by vincentcox** [khast3x/h8mail#55]
* h8mail version: Version 2.5 - "ROCKSROCKSMASSON"
* Python version: Python 3.6.9
* Operating System: Ubuntu 18.04 (same issue on Mac OS X)

### Description

I want to write an output file (`-o` flag).

### What I Did

```
h8mail -sk --local-breach dumps/non-gz/ --gzip dumps/gz/ -o example.csv -q domain -t example.com
```
<img width="677" alt="Xnip2020-03-18_10-33-40" src="https://user-images.githubusercontent.com/9286611/76946360-351b7900-6904-11ea-9a2a-c29b83db9160.png">

As you can see, no actual output is written even when there are results found.

**Comment by khast3x** [comment]
Hello,

That's odd. Can you share what data *type* h8mail found using search? Does the issue persist when searching different emails? 

Cheers

**Comment by vincentcox** [comment]
I tried with a single email target and it was the same. 
Here is some output from h8mail:
```
[>] Found occurrence [dumps/gz/ANTIPUBLIC #1.tar.gz] Line X: test@example.com:password
[>] Found occurrence [dumps/gz/ANTIPUBLIC #1.tar.gz] Line X: test@example.com:password
[>] Found occurrence [dumps/gz/ANTIPUBLIC #1.tar.gz] Line X: test@example.com:password
```

Here is the thing: I first tried it on my Mac a few weeks ago. I got the same issue with the CSV file. At that moment I thought: well maybe it's a Mac issue because the tool is developed for linux. So this week I build a password server on Ubuntu 18.04. It's a clean install so it is strange to me that it's again the same issue.

Is there a way to provide you with debug information so I can help you pinpoint the issue?

**Comment by khast3x** [comment]
hello,

Ran additional tests, still cannot reproduce the bug.  
Yes, you can email me the details at `k AT khast3x . club`

Cheers

**Comment by diazepam69** [comment]
Same issue here, Ubuntu 16 and h8mail 2.5. Testing with COMBO Leak 3.2 Bilion

**Comment by fiskeren** [comment]
Yeah, having the same problem. 

```bash
$ h8mail -v
                  Official h8mail posts:
                  https://khast3x.club/tags/h8mail/


          Version 2.5.5 - "ROCKSMASSON.5"

        ._____. ._____.     ;____________;
        | ._. | | ._. |     ;   h8mail   ;
        | !_| |_|_|_! |     ;------------;
        !___| |_______!  Heartfelt Email OSINT
        .___|_|_| |___.    Use responsibly
        | ._____| |_. | ;____________________;
        | !_! | | !_! | ; github.com/khast3x ;
        !_____! !_____! ;--------------------;

[>] h8mail is up to date

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

**Comment by khast3x** [comment]
Hello,

@fiskeren can you share which options you used and what the output was ? 
Also, could someone retry using the `--json output.json` argument and sharing the result ? I still cannot reproduce this bug, I need to know if the problem comes from the internal data parsing or the actual CSV function.  

Cheers

**Comment by fiskeren** [comment]
Hi @khast3x 

I used the following command (just as your example from https://khast3x.club/posts/2021-02-17-h8mail-with-COMB/):
```
$ h8mail -t example.com -sk -lb ./data/ --loose -o example.txt
$ cat example.txt
Target,Type,Data
```

With json instead:
```
$ h8mail -t example.com -sk -lb ./data/ --loose --json output.json
$ cat output.json
{"targets": [{"target": "example.com", "pwn_num": 98902, "data": []}]}
```

**Comment by jonathandkyle** [comment]
I am having what I think is the same issue. When I run no output is written for either json or csv. May just be an ID10T error on my end, but I have tried several ways without success. Looks like it found a lot just cant see the results. Is there a way to display results in the terminal instead?

**Comment by towel** [comment]
Can confirm this is still an issue, 2.5.5 on Mint 20.1

**Comment by jonathandkyle** [comment]
I will run it today and see if I get no output.


Respectfully,


Jonathan Kyle

Security Practice Manager

864-367-4537

***@***.******@***.***>

lockstepgroup.com



[lsg-logo-screen]<http://www.lockstepgroup.com/>
Send Me Files Securely<https://www.dropbox.com/request/Wkvf5LhfCZfg2WSUMCr5>

________________________________

**Comment by marymarysmith669** [comment]
Hi,
did someone manage to fix the issue with the empty output file? 
I've tried h8mail in Ubuntu, Windows 10, Kali Linux but in all of them I have only " Target,Type,Data" text but nothing else as a result. 
And I have over 1k  Breach Found. 
I've tried -o example.txt, -o example.csv , --j example.json but still no luck.
Can someone help me? 
Thanks in advance.

**Comment by jonathandkyle** [comment]
I got it to work. I have updated kali and h8mail. Run the --debug and you may see where it fails. Not sure what changed, it just started working for me. csv works now too.

**Comment by marymarysmith669** [comment]
Unfortunately after update kali and h8mail still no luck.
I hope someone can help me .
Cheers

**Comment by marymarysmith669** [comment]
h8mail -t @target -lb /home/kali/Desktop/Hits.txt --loose -o /home/kali/Desktop/123123.csv  -sk --debug
                  Official h8mail posts: 
                  https://khast3x.club/tags/h8mail/                          
                                                                             
                                                                             
          Version 2.5.5 - "ROCKSMASSON.5"  
 
        ._____. ._____.     ;____________;
        | ._. | | ._. |     ;   h8mail   ;
        | !_| |_|_|_! |     ;------------;
        !___| |_______!  Heartfelt Email OSINT
        .___|_|_| |___.    Use responsibly
        | ._____| |_. | ;____________________;
        | !_! | | !_! | ; github.com/khast3x ;
        !_____! !_____! ;--------------------;
 
[>] h8mail is up to date
[~] Removing duplicates
[>] Targets:
[>] @target
[~] Target factory started for @target
 DEBUG: Created target object for @target
[~] Using file /home/kali/Desktop/Hits.txt
[~] Worker [1163] is searching for targets in /home/kali/Desktop/Hits.txt (0 MB)                                                                          
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 0: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 1: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 2: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 3: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 4: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 5: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 6: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 7: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 8: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 9: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 10: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 11: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 12: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 13: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 14: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 15: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 16: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 17: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 18: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 19: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 20: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 21: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 22: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 23: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 24: target
[>] Found occurrence [/home/kali/Desktop/Hits.txt] Line 25: target
[~] Terminating worker pool
Traceback (most recent call last):
  File "/usr/local/bin/h8mail", line 8, in <module>
    sys.exit(main())
  File "/home/kali/.local/lib/python3.9/site-packages/h8mail/utils/run.py", line 371, in main
    h8mail(user_args)
  File "/home/kali/.local/lib/python3.9/site-packages/h8mail/utils/run.py", line 204, in h8mail
    breached_targets = local_to_targets(
  File "/home/kali/.local/lib/python3.9/site-packages/h8mail/utils/localsearch.py", line 33, in local_to_targets
    c.debug_news(f"DEBUG: Found following content matching {t.target.target}")
AttributeError: 'str' object has no attribute 'target'

This is what I receive

**Comment by jonathandkyle** [comment]
Just a guess, but did you set the config file? I think you have to run the config file in the command

**Comment by khast3x** [comment]
Lacking update, closing. Feel free to reopen an issue if the problem persists

**Comment by griveralfie** [comment]
@khast3x please reopen this issue

I am having the same problem when running on local breaches, searching with -t domain.com --loose

This is version 2.5.5, the latest docker image. The contents of the output files are below

CSV:
`Target,Type,Data
`

JSON:
`{"targets": [{"target": "domain.com", "pwn_num": 487, "data": []}]}`

**Comment by YankeeNightmare** [comment]
Also running in to the same problem. CSV with the following is empty, though many results were found.

`h8mail -q domain -t example.com -lb Collection\ 1/ -o pwn.csv -sk`

```
                                   Session Recap:


                 Target                  |                   Status
__________________________________________________________________________________________

            example.com            |         Breach Found (1466 elements)
__________________________________________________________________________________________

Execution time (seconds):   142.50009608268738

[>] Writing to CSV
```

```
cat pwn.csv
Target,Type,Data
```

With debug:

`h8mail -q domain -t example.com -lb Collection\ 1/ -o pwn.csv -sk --debug`

```
Traceback (most recent call last):
  File "/usr/bin/h8mail", line 33, in <module>
    sys.exit(load_entry_point('h8mail==2.5.6', 'console_scripts', 'h8mail')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/h8mail/utils/run.py", line 371, in main
    h8mail(user_args)
  File "/usr/lib/python3/dist-packages/h8mail/utils/run.py", line 204, in h8mail
    breached_targets = local_to_targets(
                       ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/h8mail/utils/localsearch.py", line 33, in local_to_targets
    c.debug_news(f"DEBUG: Found following content matching {t.target.target}")
                                                            ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'target'
```
