### ISSUE TITLE
GitHub's API limit causes software to crash on startup

### ISSUE THREAD

**Issue by Sarmacid** [khast3x/h8mail#74]
* h8mail version: 2.5.2
* Python version: 3.8.2
* Operating System: WSL

### Description

I tried to run h8mail but the request to get the latest version is failing due to GitHub's API rate limit being reached so I'm unable to get it to work at all.

### What I Did

```
❯ h8mail
          Check out the new wiki! 
          https://bit.ly/37xaQVh

 
          Version 2.5.2 - "ROCKSMASSON.2"  
  
        ._____. ._____.     ;____________;
        | ._. | | ._. |     ;   h8mail   ;
        | !_| |_|_|_! |     ;------------;
        !___| |_______!  Heartfelt Email OSINT
        .___|_|_| |___.    Use responsibly
        | ._____| |_. | ;____________________;
        | !_! | | !_! | ; github.com/khast3x ;
        !_____! !_____! ;--------------------;
 
Traceback (most recent call last): 
  File "/home/santigut/.local/share/virtualenvs/santigut-ruTPXoBT/bin/h8mail", line 8, in <module>
    sys.exit(main()) 
  File "/home/santigut/.local/share/virtualenvs/santigut-ruTPXoBT/lib/python3.8/site-packages/h8mail/utils/run.py", line 354, in main
    check_latest_version()
  File "/home/santigut/.local/share/virtualenvs/santigut-ruTPXoBT/lib/python3.8/site-packages/h8mail/utils/helpers.py", line 179, in check_latest_version
    latest = data["tag_name"]
KeyError: 'tag_name'
```

Here's the request I tried manually (with my IP redacted):

```
>>> import requests 
>>> requests.request(url="https://api.github.com/repos/khast3x/h8mail/releases/latest", method="GET").json() 
{'message': "API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://developer.github.com/v3/#rate-limiting'}
```

**Comment by khast3x** [comment]
Hello,

I'll include a fix in the next version.  
Closing for now, expect it to be fix at the next update.

Cheers
