### ISSUE TITLE
ImportError: attempted relative import with no known parent package Gitbash Windows 10 "winpty python.exe h8mail -t beep@gmail.com" command

### ISSUE THREAD

**Issue by iXanderM** [khast3x/h8mail#81]
[* h8mail version:not sure but i the used latest version for today
* Python version: 3.8
* Operating System: windows 10

### Description

Describe what you were trying to get done.
 - run h8mail with ```winpty python.exe h8mail -t beep@gmail.com```
Tell us what happened, what went wrong, and what you expected to happen.
what happened - it said:
```Traceback (most recent call last):
  File "C:\Users\Beep\AppData\Local\Programs\Python\Python38\lib\runpy.py", l
ine 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Beep\AppData\Local\Programs\Python\Python38\lib\runpy.py", l
ine 87, in _run_code
    exec(code, run_globals)
  File "h8mail\__main__.py", line 2, in <module>
    from .utils.run import main
ImportError: attempted relative import with no known parent package
```

### What I Did
Nothing yet
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
~beep@DESKTOP-beep MINGW64 /D/beep/Git/h8mail (master)
$ cd /D/beep/Git/h8mail

beep@DESKTOP-beep MINGW64 /D/beep/Git/h8mail (master)
$ winpty python.exe h8mail -t beep@gmail.com
Traceback (most recent call last):
  File "C:\Users\beep\AppData\Local\Programs\Python\Python38\lib\runpy.py", l
ine 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\beep\AppData\Local\Programs\Python\Python38\lib\runpy.py", l
ine 87, in _run_code
    exec(code, run_globals)
  File "h8mail\__main__.py", line 2, in <module>
    from .utils.run import main
ImportError: attempted relative import with no known parent package~```
^is what Git Bash looks like (changed specific info to "beep")

**Comment by khast3x** [comment]
It seems your python and pip installation is incomplete, probably something to do with PATH. Chec the troubleshooting section of the wiki
